const fs = require("fs");

function parseExistingContext(contextPath) {
  if (!fs.existsSync(contextPath)) return null;
  const content = fs.readFileSync(contextPath, "utf-8");

  const archMatch = content.match(
    /## 🏗️ Architecture Notes\n([\s\S]*?)(?=\n## )/,
  );
  const neverMatch = content.match(
    /## 🚫 Never Do\n([\s\S]*?)(?=\n---|\n## |$)/,
  );

  const archContent = archMatch ? archMatch[1].trim() : "";
  const neverContent = neverMatch ? neverMatch[1].trim() : "";

  const hasArch = archContent.length > 0 && !archContent.startsWith("<!--");
  const hasNever = neverContent.length > 0 && !neverContent.startsWith("<!--");

  if (!hasArch && !hasNever) return null;
  return {
    architectureNotes: hasArch ? archContent : null,
    neverDo: hasNever ? neverContent : null,
  };
}

function buildTreeString(fileTree) {
  const lines = [];
  const capped = fileTree.slice(0, 100);

  for (const entry of capped) {
    const indent = "  ".repeat(entry.depth);
    if (entry.type === "dir") {
      lines.push(`${indent}📁 ${entry.name}/`);
    } else {
      lines.push(`${indent}📄 ${entry.name}`);
    }
  }

  if (fileTree.length > 100) {
    lines.push(`  ... and ${fileTree.length - 100} more files`);
  }

  return lines.join("\n");
}

function generateContextMd(analysis, fileTree, preserved = null) {
  const treeString = buildTreeString(fileTree);
  const now = new Date().toISOString().split("T")[0];

  const stackLines = analysis.stack.map((s) => `- ${s}`).join("\n");
  const conventionLines =
    analysis.conventions.length > 0
      ? analysis.conventions.map((c) => `- ${c}`).join("\n")
      : "- No conventions auto-detected — add your own below";

  const scriptLines =
    Object.entries(analysis.scripts).length > 0
      ? Object.entries(analysis.scripts)
          .map(
            ([k, v]) => `- \`${analysis.packageManager} run ${k}\` → \`${v}\``,
          )
          .join("\n")
      : "- No scripts found";

  const rulesLines =
    analysis.extraRules.length > 0
      ? analysis.extraRules.map((r) => `- ${r}`).join("\n")
      : "- No auto-detected rules";

  // Key info section (only show detected items)
  const keyInfo = [
    analysis.auth ? `- **Auth**: ${analysis.auth}` : null,
    analysis.api ? `- **API**: ${analysis.api}` : null,
    analysis.validation ? `- **Validation**: ${analysis.validation}` : null,
    analysis.bundler ? `- **Bundler**: ${analysis.bundler}` : null,
    analysis.linter ? `- **Linter**: ${analysis.linter}` : null,
    analysis.formatter ? `- **Formatter**: ${analysis.formatter}` : null,
  ]
    .filter(Boolean)
    .join("\n");

  const keyInfoSection = keyInfo
    ? `\n## 🔧 Tooling & Libraries\n${keyInfo}\n`
    : "";

  const archSection = preserved?.architectureNotes
    ? preserved.architectureNotes
    : `<!-- FILL THIS IN — this is the MOST VALUABLE part of this file -->
<!-- Describe your app in 5–15 bullet points. Think about:
  - How does data flow? (request → controller → service → DB → response)
  - Where does auth live? How are sessions/tokens handled?
  - What patterns are used? (repository pattern, factory, etc.)
  - What are the main entry points?
  - What would surprise a new developer?
Example:
  - "Auth is handled by NextAuth.js. Session available via getServerSession()."
  - "All API calls route through /lib/api.ts — never use fetch() directly."
  - "We use the repository pattern. Data access only through /services."
-->`;

  const neverSection = preserved?.neverDo
    ? preserved.neverDo
    : `<!-- Add 5–10 rules the AI must NEVER break in this project -->
<!-- Be specific to YOUR codebase, not generic advice.
Example:
  - "Never use class components — we only use function components with hooks"
  - "Never commit .env files — all secrets are in Vercel env settings"  
  - "Never use useState for server data — use TanStack Query"
  - "Never import from @/utils/old — that directory is deprecated"
-->`;

  const monorepoSection =
    analysis.isMonorepo && analysis.packages.length > 0
      ? `\n## 📦 Monorepo Packages\n${analysis.packages.map((p) => `- \`${p.path}\` — ${p.name}`).join("\n")}\n`
      : "";

  return `# Project Context: ${analysis.name}
> Auto-generated by **codebrief** on ${now}
> Edit this file freely — especially the Architecture Notes and Never Do sections.

---

## 🧱 Tech Stack
${stackLines}
${monorepoSection}${keyInfoSection}
## 📁 Folder Conventions
${conventionLines}

## 🔧 Available Scripts
${scriptLines}

## 🗂️ Project Structure
\`\`\`
${treeString}
\`\`\`

## 🏗️ Architecture Notes
${archSection}

## 🤖 Rules for AI (Auto-detected)
${rulesLines}

## 🚫 Never Do
${neverSection}

---
*Auto-generated by [codebrief](https://www.npmjs.com/package/codebrief). Re-run \`codebrief --update\` after major refactors.*
`;
}

function generateCursorRule(analysis) {
  const stackLines = analysis.stack.map((s) => `- ${s}`).join("\n");
  const rulesLines = analysis.extraRules.map((r) => `- ${r}`).join("\n");

  const authLine = analysis.auth
    ? `\n## Auth\n- Authentication: ${analysis.auth}\n`
    : "";
  const dbLine = analysis.database
    ? `\n## Database\n- ${analysis.database}\n`
    : "";

  return `---
description: Auto-generated project rules for ${analysis.name}
alwaysApply: true
---

# ${analysis.name} — Cursor Project Rules
> Auto-generated by [codebrief](https://www.npmjs.com/package/codebrief)

## Tech Stack
${stackLines}

## Package Manager
Always use \`${analysis.packageManager}\`. Never suggest a different package manager.
${authLine}${dbLine}
## Code Conventions
${rulesLines || "- Follow existing patterns in the codebase"}

## Folder Structure
${analysis.conventions.map((c) => `- ${c}`).join("\n") || "- See CONTEXT.md for folder structure"}

## Important
- Read CONTEXT.md in the project root for full architecture context
- Never modify files in node_modules, dist, or build directories
- Ask before adding new dependencies
- Match the existing code style and patterns
`;
}

function generateVSCodeInstructions(analysis) {
  const stackLines = analysis.stack.join(", ");
  const authLine = analysis.auth ? `\n## Auth\n- ${analysis.auth}\n` : "";
  const dbLine = analysis.database
    ? `\n## Database\n- ${analysis.database}\n`
    : "";

  return `# Copilot Instructions: ${analysis.name}
> Auto-generated by [codebrief](https://www.npmjs.com/package/codebrief)

## Stack
${stackLines}

## Package Manager
Use \`${analysis.packageManager}\` for all commands.
${authLine}${dbLine}
## Conventions
${analysis.conventions.map((c) => `- ${c}`).join("\n") || "- No conventions detected"}

## Rules
${analysis.extraRules.map((r) => `- ${r}`).join("\n") || "- Follow existing patterns"}

## Important
- Read CONTEXT.md in the project root for full architecture context
- Match the existing code style and patterns
`;
}

module.exports = {
  generateContextMd,
  generateCursorRule,
  generateVSCodeInstructions,
  parseExistingContext,
};
